package Vistas.Login;

import DAO.UsuarioTIDAO;
import Modelos.UsuarioTI;
import Vistas.JefeArea.frmJefeArea;
import Vistas.JefeArea.frmSolicitudJefeArea;
import Vistas.Tecnico.frmSolicitudTecnico;
import Vistas.Tecnico.frmTecnico;
import javax.swing.JOptionPane;

public class frmLoginUsuarioTI extends javax.swing.JFrame {

    UsuarioTIDAO udao;
    UsuarioTI uti;
    frmTecnico frmt;
    frmJefeArea frmja;

    public frmLoginUsuarioTI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtuserti = new javax.swing.JTextField();
        txtpassti = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Ingresar.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 120, 40));

        txtuserti.setBackground(new java.awt.Color(198, 198, 198));
        txtuserti.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtuserti.setBorder(null);
        getContentPane().add(txtuserti, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 302, 300, 30));

        txtpassti.setBackground(new java.awt.Color(198, 198, 198));
        txtpassti.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtpassti.setBorder(null);
        getContentPane().add(txtpassti, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login Usuario TI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udao = new UsuarioTIDAO();
        String usuario = txtuserti.getText();
        String contrasena = txtpassti.getText();

        if (txtuserti.getText().equals("") && txtpassti.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese usuario y contraseña", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        } else if (txtuserti.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese usuario", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        } else if (txtpassti.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese contraseña", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        } else {
            uti = udao.autenticar(usuario, contrasena);
            if (uti == null) {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            } else if (uti.getRol().getIdRol() == 1) {
                frmTecnico.nombres = uti.getPersona().getNombres();
                frmSolicitudTecnico.nombres = uti.getPersona().getNombres();
                frmt = new frmTecnico();
                udao.estadoconexion(uti.getUsuario(), 1);
                frmt.setUsuarioT(uti.getUsuario());
                frmt.setVisible(true);
                this.dispose();
            } else if (uti.getRol().getIdRol() == 2) {
                frmJefeArea.nombres = uti.getPersona().getNombres();
                frmSolicitudJefeArea.nombres = uti.getPersona().getNombres();
                frmja = new frmJefeArea();
                udao.estadoconexion(uti.getUsuario(), 1);
                frmja.setUsuarioJ(uti.getUsuario());
                frmja.setVisible(true);
                this.dispose();
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuarioTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuarioTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuarioTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuarioTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoginUsuarioTI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtpassti;
    private javax.swing.JTextField txtuserti;
    // End of variables declaration//GEN-END:variables
}
