package Vistas.Tecnico;

import DAO.CategoriaDAO;
import DAO.Estado_solicitudDAO;
import DAO.PrioridadDAO;
import DAO.SolicitudDAO;
import DAO.TipoDAO;
import DAO.UsuarioTIDAO;
import Modelos.Categoria;
import Modelos.Estado_solicitud;
import Modelos.Prioridad;
import Modelos.Solicitud;
import Modelos.Tipo_solicitud;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class frmSolicitudTecnico extends javax.swing.JFrame {

    SolicitudDAO sd = new SolicitudDAO();
    CategoriaDAO cat = new CategoriaDAO();
    PrioridadDAO pri = new PrioridadDAO();
    UsuarioTIDAO udao;
    TipoDAO ts = new TipoDAO();
    Estado_solicitudDAO esd = new Estado_solicitudDAO();
    private String usuarioT;
    public static String nombres;
    Solicitud s = frmTecnico.sol;

    public String getUsuarioT() {
        return usuarioT;
    }

    public void setUsuarioT(String usuarioT) {
        this.usuarioT = usuarioT;
    }

    public frmSolicitudTecnico() {
        initComponents();
        txtDescripcion.setBorder(BorderFactory.createCompoundBorder(txtDescripcion.getBorder(), BorderFactory.createEmptyBorder(3, 7, 3, 7)));
        llenarCombos();
        iniciarDatos();
        this.setTitle(nombres);
        this.setLocationRelativeTo(null);
    }
    
    private void cerrar() {
        try {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de salir de la aplicación?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                udao = new UsuarioTIDAO();
                udao.estadoconexion(this.getUsuarioT(), 2);
                System.exit(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void iniciarDatos() {
        String tecnico;
        if (s.getUsuarioTI().getPersona().getNombres() == null) {
            tecnico = "Sin Asignar";
        } else {
            tecnico = s.getUsuarioTI().getPersona().getNombres();
        }
        lblCliente.setText(s.getUsuario().getPersona().getNombres());
        lblTecnico.setText(tecnico);
        lblAsunto.setText(s.getAsunto());
        txtDescripcion.setText(s.getDescripcion());
        cboCategoria.setSelectedIndex(s.getCat().getIdCategoria() - 1);
        cboEstado.setSelectedIndex(s.getEs().getIdEstado_solicitud() - 1);
        cboPrioridad.setSelectedIndex(s.getPri().getIdPrioridad() - 1);
        cboTipo.setSelectedIndex(s.getTs().getIdTipo_solicitud() - 1);
    }

    void llenarCombos() {
        cboCategoria.removeAllItems();
        cboPrioridad.removeAllItems();
        cboTipo.removeAllItems();
        cboEstado.removeAllItems();

        ArrayList mListaCat = cat.consultaCat();
        ArrayList mListaPri = pri.consultaPri();
        ArrayList mListaTip = ts.consultaTipo();
        ArrayList mListaEst = esd.consultaES();

        Iterator iteraCat = mListaCat.iterator();
        while (iteraCat.hasNext()) {
            Categoria objCat = (Categoria) iteraCat.next();
            cboCategoria.addItem(objCat);
        }

        Iterator iteraPri = mListaPri.iterator();
        while (iteraPri.hasNext()) {
            Prioridad objPri = (Prioridad) iteraPri.next();
            cboPrioridad.addItem(objPri);
        }

        Iterator iteraTS = mListaTip.iterator();
        while (iteraTS.hasNext()) {
            Tipo_solicitud objTS = (Tipo_solicitud) iteraTS.next();
            cboTipo.addItem(objTS);
        }

        Iterator iteraES = mListaEst.iterator();
        while (iteraES.hasNext()) {
            Estado_solicitud objES = (Estado_solicitud) iteraES.next();
            cboEstado.addItem(objES);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        cboPrioridad = new javax.swing.JComboBox<>();
        cboTipo = new javax.swing.JComboBox<>();
        cboEstado = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblAsunto = new javax.swing.JLabel();
        lblTecnico = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboCategoria.setBackground(new java.awt.Color(241, 163, 163));
        cboCategoria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 300, 30));

        txtDescripcion.setBackground(new java.awt.Color(241, 163, 163));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 610, 150));

        cboPrioridad.setBackground(new java.awt.Color(241, 163, 163));
        cboPrioridad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(cboPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 130, 30));

        cboTipo.setBackground(new java.awt.Color(241, 163, 163));
        cboTipo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(cboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 130, 30));

        cboEstado.setBackground(new java.awt.Color(241, 163, 163));
        cboEstado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 300, 30));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Salir Rojo.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 40, 40));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Actualizar Rojo.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, 40));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setToolTipText("");
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 113, 250, 30));

        lblAsunto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAsunto.setForeground(new java.awt.Color(255, 255, 255));
        lblAsunto.setToolTipText("");
        getContentPane().add(lblAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 272, 250, 30));

        lblTecnico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lblTecnico.setToolTipText("");
        getContentPane().add(lblTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 186, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventana Gestor Solicitud (Tecnico).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 668, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        frmTecnico frm = new frmTecnico();
        frm.setVisible(true);
        frm.setUsuarioT(this.usuarioT);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        sd = new SolicitudDAO();
        Solicitud obj = frmTecnico.sol;
        obj.setEs(new Estado_solicitud(cboEstado.getSelectedIndex() + 1));
        obj.setCat(new Categoria(cboCategoria.getSelectedIndex() + 1));
        obj.setPri(new Prioridad(cboPrioridad.getSelectedIndex() + 1));
        obj.setDescripcion(txtDescripcion.getText());
        switch (obj.getEs().getIdEstado_solicitud()) {
            case 2:
                sd.atenderSolicitud(obj);
                break;
            case 3:
                sd.cierreSolicitud(obj);
                break;
        }
        JOptionPane.showMessageDialog(null, "Se actualizó la solicitud correctamente");
        frmTecnico frm = new frmTecnico();
        frm.setVisible(true);
        frm.setUsuarioT(this.usuarioT);
        this.dispose();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSolicitudTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Object> cboCategoria;
    private javax.swing.JComboBox<Object> cboEstado;
    private javax.swing.JComboBox<Object> cboPrioridad;
    private javax.swing.JComboBox<Object> cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
