package Vistas.JefeArea;

import DAO.CategoriaDAO;
import DAO.Estado_solicitudDAO;
import DAO.PrioridadDAO;
import DAO.SolicitudDAO;
import DAO.TipoDAO;
import DAO.UsuarioTIDAO;
import Modelos.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class frmSolicitudJefeArea extends javax.swing.JFrame {

    SolicitudDAO sda = new SolicitudDAO();
    UsuarioTIDAO uti = new UsuarioTIDAO();
    CategoriaDAO cat = new CategoriaDAO();
    PrioridadDAO pri = new PrioridadDAO();
    TipoDAO ts = new TipoDAO();
    Estado_solicitudDAO esd = new Estado_solicitudDAO();
    private String usuarioJ;
    public static String idSol;
    public static String nombres;

    public String getUsuarioJ() {
        return usuarioJ;
    }

    public void setUsuarioJ(String usuarioJ) {
        this.usuarioJ = usuarioJ;
    }

    public frmSolicitudJefeArea() {
        initComponents();
        llenarCombos();
        llenarCampos();
        txtDescripcion.setBorder(BorderFactory.createCompoundBorder(txtDescripcion.getBorder(), BorderFactory.createEmptyBorder(3, 7, 3, 7)));
        this.setTitle(nombres);
        this.setLocationRelativeTo(null);
    }

    private void cerrar() {
        try {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de salir de la aplicación?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                UsuarioTIDAO uti2 = new UsuarioTIDAO();
                uti2.estadoconexion(this.getUsuarioJ(), 2);
                System.exit(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void llenarCampos() {
        lblAsunto.setText(frmJefeArea.sol.getAsunto());
        lblCliente.setText(frmJefeArea.sol.getUsuario().getPersona().getNombres());
        txtDescripcion.setText(frmJefeArea.sol.getDescripcion());
        cmbEstado.setSelectedIndex(frmJefeArea.sol.getEs().getIdEstado_solicitud() - 1);
        cmbCategoria.setSelectedIndex(frmJefeArea.sol.getCat().getIdCategoria() - 1);
        cmbTecnicos.setSelectedIndex(frmJefeArea.sol.getUsuarioTI().getIdUsuarioTI() - 1);
        cmbPrioridad.setSelectedIndex(frmJefeArea.sol.getPri().getIdPrioridad() - 1);
        cmbTipo.setSelectedIndex(frmJefeArea.sol.getTs().getIdTipo_solicitud() - 1);
    }

    void llenarCombos() {
        cmbTecnicos.removeAllItems();
        cmbCategoria.removeAllItems();
        cmbPrioridad.removeAllItems();
        cmbTipo.removeAllItems();
        cmbEstado.removeAllItems();

        ArrayList mListaTec = uti.consultaTecnico();
        ArrayList mListaCat = cat.consultaCat();
        ArrayList mListaPri = pri.consultaPri();
        ArrayList mListaTip = ts.consultaTipo();
        ArrayList mListaEst = esd.consultaES();

        Iterator iteraTec = mListaTec.iterator();
        while (iteraTec.hasNext()) {
            UsuarioTI objTec = (UsuarioTI) iteraTec.next();
            cmbTecnicos.addItem(objTec);

        }

        Iterator iteraCat = mListaCat.iterator();
        while (iteraCat.hasNext()) {
            Categoria objCat = (Categoria) iteraCat.next();
            cmbCategoria.addItem(objCat);
        }

        Iterator iteraPri = mListaPri.iterator();
        while (iteraPri.hasNext()) {
            Prioridad objPri = (Prioridad) iteraPri.next();
            cmbPrioridad.addItem(objPri);
        }

        Iterator iteraTS = mListaTip.iterator();
        while (iteraTS.hasNext()) {
            Tipo_solicitud objTS = (Tipo_solicitud) iteraTS.next();
            cmbTipo.addItem(objTS);
        }

        Iterator iteraES = mListaEst.iterator();
        while (iteraES.hasNext()) {
            Estado_solicitud objES = (Estado_solicitud) iteraES.next();
            cmbEstado.addItem(objES);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        cmbPrioridad = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbTecnicos = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblAsunto = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnAnular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDescripcion.setBackground(new java.awt.Color(221, 170, 253));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 610, 150));

        cmbPrioridad.setBackground(new java.awt.Color(221, 170, 253));
        cmbPrioridad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbPrioridad.setBorder(null);
        getContentPane().add(cmbPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 130, 30));

        cmbEstado.setBackground(new java.awt.Color(221, 170, 253));
        cmbEstado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbEstado.setBorder(null);
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 300, 30));

        cmbCategoria.setBackground(new java.awt.Color(221, 170, 253));
        cmbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbCategoria.setBorder(null);
        getContentPane().add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 300, 30));

        cmbTecnicos.setBackground(new java.awt.Color(221, 170, 253));
        cmbTecnicos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbTecnicos.setBorder(null);
        getContentPane().add(cmbTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 30));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Salir morado.png"))); // NOI18N
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 40, 40));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Actualizar Morado.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, 40));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setToolTipText("");
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 113, 250, 30));

        lblAsunto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAsunto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 272, 250, 30));

        cmbTipo.setBackground(new java.awt.Color(221, 170, 253));
        cmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbTipo.setBorder(null);
        getContentPane().add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 130, 30));

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar Morado.png"))); // NOI18N
        btnAnular.setBorder(null);
        btnAnular.setBorderPainted(false);
        btnAnular.setContentAreaFilled(false);
        btnAnular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 519, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventana Gestor Solicitud (Jefe Area).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 668, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (cmbTecnicos.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione a un técnico");
        } else {
            sda = new SolicitudDAO();
            Solicitud obj = frmJefeArea.sol;
            obj.setEs(new Estado_solicitud(cmbEstado.getSelectedIndex() + 1));
            obj.setCat(new Categoria(cmbCategoria.getSelectedIndex() + 1));
            obj.setUsuarioTI(new UsuarioTI(cmbTecnicos.getSelectedIndex() + 1));
            obj.setPri(new Prioridad(cmbPrioridad.getSelectedIndex() + 1));
            obj.setDescripcion(txtDescripcion.getText());
            switch (obj.getEs().getIdEstado_solicitud()) {
                case 1:
                    sda.ModificarJF(obj);
                    break;
                case 2:
                    sda.atenderSolicitudJF(obj);
                    break;
                case 3:
                    sda.cierreSolicitudJF(obj);
                    break;
            }
            JOptionPane.showMessageDialog(null, "Se actualizó la solicitud correctamente");
            frmJefeArea frm = new frmJefeArea();
            frm.setVisible(true);
            frm.setUsuarioJ(this.usuarioJ);
            this.dispose();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmJefeArea frm = new frmJefeArea();
        frm.setVisible(true);
        frm.setUsuarioJ(this.usuarioJ);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar la solicitud?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            sda.eliminar(idSol);
            JOptionPane.showMessageDialog(null, "Se eliminó la solicitud correctamente");
            frmJefeArea frm = new frmJefeArea();
            frm.setVisible(true);
            frm.setUsuarioJ(this.usuarioJ);
            this.dispose();
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudJefeArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudJefeArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudJefeArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudJefeArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSolicitudJefeArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Object> cmbCategoria;
    private javax.swing.JComboBox<Object> cmbEstado;
    private javax.swing.JComboBox<Object> cmbPrioridad;
    private javax.swing.JComboBox<Object> cmbTecnicos;
    private javax.swing.JComboBox<Object> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables

}
