package Vistas.Cliente;

import DAO.SolicitudDAO;
import Modelos.Categoria;
import Modelos.Estado_solicitud;
import Modelos.Prioridad;
import Modelos.Solicitud;
import Modelos.UsuarioTI;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class frmDetalleSolicitud extends javax.swing.JFrame {

    public static String idSol;
    public static int idCat;
    public static int idPri;
    public static int tipo;
    public static int idTecnico;
    public static int idEstado;
    public static String nombres;

    SolicitudDAO obj = new SolicitudDAO();

    public frmDetalleSolicitud() {
        initComponents();
        txtDescripcion.setBorder(BorderFactory.createCompoundBorder(txtDescripcion.getBorder(), BorderFactory.createEmptyBorder(3, 7, 3, 7)));
        this.setTitle(nombres);
        this.setLocationRelativeTo(null);

    }

    private void cerrar() {
        try {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de salir de la aplicación?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblCliente = new javax.swing.JLabel();
        lblTecnico = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        lblPrioridad = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDescripcion.setBackground(new java.awt.Color(165, 212, 185));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setBorder(null);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 610, 150));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setToolTipText("");
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 113, 250, 30));

        lblTecnico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lblTecnico.setToolTipText("");
        getContentPane().add(lblTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 250, 30));

        txtAsunto.setBackground(new java.awt.Color(165, 212, 185));
        txtAsunto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAsunto.setBorder(null);
        getContentPane().add(txtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 272, 250, 30));

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 113, 285, 30));

        lblPrioridad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPrioridad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 186, 120, 30));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 186, 120, 30));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 272, 285, 30));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton salir Verde.png"))); // NOI18N
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 40, 40));

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar verde.png"))); // NOI18N
        btnAnular.setBorder(null);
        btnAnular.setBorderPainted(false);
        btnAnular.setContentAreaFilled(false);
        btnAnular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 519, -1, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Actualizar Verde.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventana Detalle Solicitud (Cliente).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 668, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmCliente regresar = new frmCliente();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Solicitud s = new Solicitud();
        s.setIdSolicitud(idSol);
        Categoria cat = new Categoria(idCat);
        s.setCat(cat);
        Estado_solicitud es = new Estado_solicitud(idEstado);
        s.setEs(es);
        UsuarioTI Uti = new UsuarioTI(idTecnico);
        s.setUsuarioTI(Uti);
        Prioridad pri = new Prioridad(idPri);
        s.setPri(pri);
        s.setAsunto(txtAsunto.getText());
        s.setDescripcion(txtDescripcion.getText());
        obj.ModificarCliente(s);
        JOptionPane.showMessageDialog(null, "Se actualizó la solicitud correctamente");
        frmCliente frm = new frmCliente();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        if (lblEstado.getText().equals("Atendiendo")) {
            JOptionPane.showMessageDialog(null, "La solicitud se encuentra en atención");
        } else {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar la solicitud?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                obj.eliminar(idSol);
                JOptionPane.showMessageDialog(null, "Se eliminó la solicitud correctamente");
                frmCliente frm = new frmCliente();
                frm.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetalleSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetalleSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetalleSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetalleSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetalleSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnActualizar;
    public static javax.swing.JButton btnAnular;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCategoria;
    public static javax.swing.JLabel lblCliente;
    public static javax.swing.JLabel lblEstado;
    public static javax.swing.JLabel lblPrioridad;
    public static javax.swing.JLabel lblTecnico;
    public static javax.swing.JLabel lblTipo;
    public static javax.swing.JTextField txtAsunto;
    public static javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
